// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const envUrl = (import.meta.env.VITE_SUPABASE_URL as string | undefined)?.trim();
const envProjectId = (import.meta.env.VITE_SUPABASE_PROJECT_ID as string | undefined)?.trim();
const envKey = (import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string | undefined)?.trim();

const SUPABASE_URL =
  envUrl ||
  (envProjectId ? `https://${envProjectId}.supabase.co` : '') ||
  'https://env-manquant.supabase.co';
const SUPABASE_PUBLISHABLE_KEY =
  envKey || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.env-manquant';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

if (SUPABASE_URL.includes('env-manquant') || SUPABASE_PUBLISHABLE_KEY.includes('env-manquant')) {
  console.error(
    '[UPG Systeme] Variables Supabase manquantes. Le formulaire de connexion peut apparaitre, ' +
      "mais les requetes d'authentification echoueront tant que VITE_SUPABASE_URL (ou PROJECT_ID) " +
      'et VITE_SUPABASE_PUBLISHABLE_KEY ne sont pas definies.',
  );
}

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});